version: "3"

services:
  server:
    build: docker
    container_name: server
    environment:
      SERVICE_PORT_HTTP: 8001
      SERVICE_PORT_GRPC: 8002
    ports:
      - "8001:8001"
      - "8002:8002"