version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    container_name: storage_service
    environment:
      SERVICE_PORT_HTTP: 8001
      SERVICE_PORT_GRPC: 8002
    ports:
      - "8001:8001"
      - "8002:8002"
    networks:
      hl-lab3-network:

  redis_1:
    image: redis:7.2.2
    container_name: redis_1
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7000:7000"
    volumes:
      - ./redis/cluster/redis_1/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.10

  redis_2:
    image: redis:7.2.2
    container_name: redis_2
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7001:7001"
    volumes:
      - ./redis/cluster/redis_2/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.11

  redis_3:
    image: redis:7.2.2
    container_name: redis_3
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7002:7002"
    volumes:
      - ./redis/cluster/redis_3/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.12


  redis_4:
    image: redis:7.2.2
    container_name: redis_4
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7003:7003"
    volumes:
      - ./redis/cluster/redis_4/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.13

  redis_5:
    image: redis:7.2.2
    container_name: redis_5
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7004:7004"
    volumes:
      - ./redis/cluster/redis_5/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.14

  redis_6:
    image: redis:7.2.2
    container_name: redis_6
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "7005:7005"
    volumes:
      - ./redis/cluster/redis_6/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.15

  redis_cluster:
    image: redis:7.2.2
    container_name: redis_cluster
    command: "redis-cli --cluster create 172.28.1.10:7000 172.28.1.11:7001 172.28.1.12:7002 172.28.1.13:7003 172.28.1.14:7004 172.28.1.15:7005 --cluster-replicas 1 --cluster-yes"
#    command: "redis-cli --cluster create localhost:7000 localhost:7001 localhost:7002 localhost:7003 localhost:7004 localhost:7005 --cluster-replicas 1 --cluster-yes"
    depends_on:
      - redis_1
      - redis_2
      - redis_3
      - redis_4
      - redis_5
      - redis_6
    ports:
      - "7006:7006"
    tty: true
    networks:
      hl-lab3-network:
        ipv4_address: 172.28.1.16

#  redis-master:
#    image: redis:7.2.2
#    container_name: master
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ./redis/replication/master/redis.conf:/usr/local/etc/redis/redis.conf
#    ports:
#      - "6380:6380"
#    networks:
#      hl-lab3-network:
#          ipv4_address: 172.28.1.4
#
#  redis-slave-1:
#    image: redis:7.2.2
#    container_name: slave-1
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ./redis/replication/slave1/redis.conf:/usr/local/etc/redis/redis.conf
#    ports:
#      - "6381:6381"
#    networks:
#      hl-lab3-network:
#        ipv4_address: 172.28.1.5
#
#  redis-slave-2:
#    image: redis:7.2.2
#    container_name: slave-2
#    command: redis-server /usr/local/etc/redis/redis.conf
#    volumes:
#      - ./redis/replication/slave2/redis.conf:/usr/local/etc/redis/redis.conf
#    ports:
#      - "6382:6382"
#    networks:
#      hl-lab3-network:
#        ipv4_address: 172.28.1.6

networks:
  hl-lab3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16