version: "3"

services:
  server:
    build:
      context: ./
      dockerfile: ./build/Dockerfile
    container_name: storage_service
    environment:
      SERVICE_PORT_HTTP: 8001
      SERVICE_PORT_GRPC: 8002
    ports:
      - "8001:8001"
      - "8002:8002"

  redis-master:
    image: redis:7.2.2
    container_name: master
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis/master/redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - "6380:6380"
    networks:
      hl-lab3-network:
          ipv4_address: 172.28.1.4

#  redis-slave:
#    image: redis:7.2.2
#    container_name: slave
#    ports:
#      - "6381:6380"
#    command: redis-server --slaveof master 6379
#    depends_on:
#      - redis-master
#    networks:
#      - hl-lab3-network

networks:
  hl-lab3-network:
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16